registros_victimas/beneficios/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base beneficios"""

urlpatterns = [
    url(r'^add_beneficio/$', 'beneficios.views.add_beneficio', name='add_beneficio'),
    url(r'^lista_beneficios/$', 'beneficios.views.lista_beneficios', name='lista_beneficios'),
    url(r'^update_beneficio/(?P<id>\d+)/$', 'beneficios.views.update_beneficio', name='update_beneficio'),
]

registros_victimas/generales/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base generales"""

urlpatterns = [
	url(r'^add_tipo_doc/$', 'generales.views.add_tipo_documento', name='add_tipo_documento'),
    url(r'^add_lugar_declaracion/$', 'generales.views.add_lugar_declaracion', name='add_lugar_declaracion'),
    url(r'^lista_lugares_declaracion/$', 'generales.views.lista_lugares_declaracion', name='lista_lugares_declaracion'),
    url(r'^lista_tipos_documento/$', 'generales.views.lista_tipos_documentos_generales', name='lista_tipos_documento'),
    url(r'^add_entidad_atencion/$', 'generales.views.add_entidad_atencion', name='add_entidad_atencion'),
    url(r'^matriz/$', 'generales.views.matriz', name='matriz'),
    url(r'^login_view/$', 'generales.views.login_view', name='login_view'),
    url(r'^index_view/$', 'generales.views.index_view', name='index_view'),
    url(r'^logout_view/$', 'generales.views.logout_view', name='logout_view'),
    url(r'^estado_clientes_view/$', 'generales.views.estado_clientes_view', name='estado_clientes_view'),
    url(r'^lista_notificaciones/(?P<id>\d+)/$', 'generales.views.lista_notificaciones', name='lista_notificaciones'),
    url(r'^notificaciones/$', 'generales.views.notificaciones', name='notificaciones'),
    url(r'^info/$', 'generales.views.info', name='info'),
]

registros_victimas/registros_victimas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^generales/', include('generales.urls', namespace='generales')),
    url(r'^solicitantes/', include('solicitantes.urls', namespace='solicitantes')),
    url(r'^beneficios/', include('beneficios.urls', namespace='beneficios')),
    url(r'^admin/', include(admin.site.urls)),
]

registros_victimas/beneficios/models.py
from django.db import models


class Derecho(models.Model):
    nombre_componente_politica = models.CharField(max_length=50)
    nombre_derecho = models.CharField(max_length=50)

    class Meta: 
        verbose_name_plural = 'Derechos involucrados'

    def __unicode__(self): 
        return self.nombre_derecho

class BeneficioVictima(models.Model):
    derecho = models.ForeignKey('Derecho')
    condiciones_problematica = models.CharField(max_length=1024)
    nombre_programa = models.CharField(max_length=100)
    estado_gestion_programa = models.CharField(max_length=50)
    meta_programa = models.CharField(max_length=1024)
    avance_meta_programa = models.BigIntegerField(blank=True, null=True)
    indicadores = models.BigIntegerField(blank=True, null=True)
    coofinanciacion_nacional = models.BigIntegerField(blank=True, null=True)
    fosyga_etesa = models.BigIntegerField(blank=True, null=True)
    otros_recursos_nacionales = models.BigIntegerField(blank=True, null=True)
    coofinanciacion_departamental = models.BigIntegerField(blank=True, null=True)
    otros_recursos_departamentales = models.BigIntegerField(blank=True, null=True)
    recursos_propios = models.BigIntegerField(blank=True, null=True)
    sistema_general_participacion = models.BigIntegerField(blank=True, null=True)
    regalia = models.BigIntegerField(blank=True, null=True)
    credito = models.BigIntegerField(blank=True, null=True)
    otros_recursos_municipales = models.BigIntegerField(blank=True, null=True)
    empresa_privada = models.BigIntegerField(blank=True, null=True)
    cooperacion_otros = models.BigIntegerField(blank=True, null=True)
    otros = models.BigIntegerField(blank=True, null=True)
    participacion_nacional = models.CharField(max_length=1024, blank=True, null=True)
    participacion_departamental = models.CharField(max_length=1024, blank=True, null=True)
    participacion_municipal = models.CharField(max_length=1024, blank=True, null=True)
    cooperacion_internacional = models.CharField(max_length=1024, blank=True, null=True)
    participacion_otros = models.CharField(max_length=1024, blank=True, null=True)

    class Meta: 
        verbose_name_plural = 'Beneficios'

    def __unicode__(self): 
        return self.nombre_programa

registros_victimas/beneficios/forms.py
# -*- coding: 850 -*-
from django import forms
from beneficios.models import *
from generales.models import *


"""Las clases form estructuran el formulario que se presentará al usuario a partir de la entidad de la base de datos que se requiera instanciar,
se construye la clase meta donde se tiene el model (modelo o entidad de la base de datos), fields(los campos de la entidad de la bd que serán 
llamados), labels(los campos llamados y sus respectivas etiquetas a presentar al usuario) y widgets(los campos llamados y el tipo de componente
que será usado para diligenciar cada campo como tipo campo de texto, cuadro de texto, numérico, email, desplegable, etc.)"""

class beneficioVictimaForm(forms.ModelForm):

    class Meta:
        model = BeneficioVictima
        fields = [
            'derecho',
            'condiciones_problematica',
            'nombre_programa',
            'estado_gestion_programa',
            'meta_programa',
            'avance_meta_programa',
            'indicadores',
            'coofinanciacion_nacional',
            'fosyga_etesa',
            'otros_recursos_nacionales',
            'coofinanciacion_departamental',
            'otros_recursos_departamentales',
            'recursos_propios',
            'sistema_general_participacion',
            'regalia',
            'credito',
            'otros_recursos_municipales',
            'empresa_privada',
            'cooperacion_otros',
            'otros',
            'participacion_nacional',
            'participacion_departamental',
            'participacion_municipal',
            'cooperacion_internacional',
            'participacion_otros',
        ]
        labels = {
            'derecho': 'Derecho (*)',
            'condiciones_problematica': 'Condiciones de la problemática (*)',
            'nombre_programa': 'Nombre del programa (*)',
            'estado_gestion_programa': 'Estado de la gestión del programa (*)',
            'meta_programa': 'Meta del programa (*)',
            'avance_meta_programa': 'Avance de la meta del programa',
            'indicadores': 'Indicadores',
            'coofinanciacion_nacional': 'Coofinanciación nacional',
            'fosyga_etesa': 'FOSYGA y ETESA',
            'otros_recursos_nacionales': 'Otros recursos nacionales',
            'coofinanciacion_departamental': 'Coofinanciación departamental',
            'otros_recursos_departamentales': 'Otros recursos departamentales',
            'recursos_propios': 'Recursos propios',
            'sistema_general_participacion': 'Sistema general de participación',
            'regalia': 'Regalía',
            'credito': 'Crédito',
            'otros_recursos_municipales': 'Otros recursos municipales',
            'empresa_privada': 'Empresa privada',
            'cooperacion_otros': 'Cooperación de otros',
            'otros': 'Otros',
            'participacion_nacional': 'Participación nacional',
            'participacion_departamental': 'Participación departamental',
            'participacion_municipal': 'Participación municipal',
            'cooperacion_internacional': 'Cooperación internacional',
            'participacion_otros': 'Participación de otros',
        }
        widgets = {
            'derecho': forms.Select(attrs={'class': 'form-control'}),
            'condiciones_problematica': forms.Textarea(attrs={'class': 'form-control'}),
            'nombre_programa': forms.TextInput(attrs={'class': 'form-control'}),
            'estado_gestion_programa': forms.TextInput(attrs={'class': 'form-control'}),
            'meta_programa': forms.Textarea(attrs={'class': 'form-control'}),
            'avance_meta_programa': forms.NumberInput(attrs={'class': 'form-control'}),
            'indicadores': forms.NumberInput(attrs={'class': 'form-control'}),
            'coofinanciacion_nacional': forms.NumberInput(attrs={'class': 'form-control'}),
            'fosyga_etesa': forms.NumberInput(attrs={'class': 'form-control'}),
            'otros_recursos_nacionales': forms.NumberInput(attrs={'class': 'form-control'}),
            'coofinanciacion_departamental': forms.NumberInput(attrs={'class': 'form-control'}),
            'otros_recursos_departamentales': forms.NumberInput(attrs={'class': 'form-control'}),
            'recursos_propios': forms.NumberInput(attrs={'class': 'form-control'}),
            'sistema_general_participacion': forms.NumberInput(attrs={'class': 'form-control'}),
            'regalia': forms.NumberInput(attrs={'class': 'form-control'}),
            'credito': forms.NumberInput(attrs={'class': 'form-control'}),
            'otros_recursos_municipales': forms.NumberInput(attrs={'class': 'form-control'}),
            'empresa_privada': forms.NumberInput(attrs={'class': 'form-control'}),
            'cooperacion_otros': forms.NumberInput(attrs={'class': 'form-control'}),
            'otros': forms.NumberInput(attrs={'class': 'form-control'}),
            'participacion_nacional': forms.Textarea(attrs={'class': 'form-control'}),
            'participacion_departamental': forms.Textarea(attrs={'class': 'form-control'}),
            'participacion_municipal': forms.Textarea(attrs={'class': 'form-control'}),
            'cooperacion_internacional': forms.Textarea(attrs={'class': 'form-control'}),
            'participacion_otros': forms.Textarea(attrs={'class': 'form-control'}),
        }

registros_victimas/beneficios/views.py
# -*- coding: 850 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from beneficios.models import *
from beneficios.forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


"""La función hace una captura de la entidad BeneficioVictima de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_beneficios(request):
    beneficios = BeneficioVictima.objects.all()
    paginator = Paginator(beneficios, 10) # muestra 10 contactos por página

    page = request.GET.get('page')
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_beneficios.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función agrega un nuevo registro a la entidad de la base de datos correspondiente, el proceso de validación se hace
mediante un formulario estructurado a partir de la misma entidad de la base de datos."""
def add_beneficio(request):
    informacion = "inicializando"
    titulo="Nuevo beneficio"
    if request.method == 'GET':
        form = beneficioVictimaForm()
        ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
        return render_to_response('add.html', 
            ctx,
            context_instance=RequestContext(request)
        )
    else:
        form = beneficioVictimaForm(request.POST)
        if form.is_valid():
            form.save()
            informacion = "Guardado"
        else:
            informacion = "Error"
        return render_to_response(
            'add.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
    return render_to_response('add.html', 
        ctx,
        context_instance=RequestContext(request)
    )


"""La función obtiene un registro de la entidad correspondiente de la base de datos a partir de su id, hace uso
de un formulario estructurado a partir de la misma entidad y actualiza los datos en el mismo registro consultado."""
def update_beneficio(request, id):
    beneficio = BeneficioVictima.objects.get(id=id)
    informacion = "Procesando"
    titulo="Actualizar datos del beneficio"
    if request.method == 'GET':
        form = beneficioVictimaForm(instance=beneficio)
    else:
        form = beneficioVictimaForm(request.POST, instance=beneficio)
        if form.is_valid():
            form.save()
            informacion = "Guardado"
        else:
            informacion = "Error"
        return render_to_response(
            'add.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
    return render_to_response('add.html', 
        ctx,
        context_instance=RequestContext(request)
    )

registros_victimas/beneficios/templates/add.html
{% extends 'base.html' %}

{% block content %}

<form class="form-horizontal" method="post">{% csrf_token %}
    <fieldset>
        <legend>{{ titulo }}</legend>
        {% for field in form %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                        {% if field.required = True %}
                            <p class="help-inline"><small>dsfdfs</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% if "Guardado" in informacion %}
    <script type="text/javascript">
    swal('Guardado!', 'El registro ha sido guardado satisfactoriamente', 'success');
    </script>
{% endif %}
{% if "Eliminado" in informacion %}
    <script type="text/javascript">
    swal('Eliminado!', 'El registro se ha borrado satisfactoriamente', 'sucess');
    </script>
{% endif %}
{% if "Error" in informacion %}
    <script type="text/javascript">
    swal('Error!', 'Verifique que los campos se encuentren bien diligenciados', 'error');
    </script>
{% endif %}


{% endblock content %}


registros_victimas/beneficios/templates/lista_beneficios.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>Beneficios disponibles</h3>
		<div style="width:100%; overflow: scroll; overflow-y: hidden;">
		<table class="table table-bordered table-hover table-striped table-reflow tabla">
	  		<ul>
	  		<tr>
				<th>ID</th>
				<th>Nombre del programa</th>
				<th>Estado de gestión del programa</th>
				<th>Meta</th>
				<th>Acciones</th>
			</tr>
		{% for i in registros %}
		<tr>
			<td>{{i.id}}</td>
			<td>{{i.nombre_programa}}</td>
			<td>{{i.estado_gestion_programa}}</td>
			<td>{{i.meta_programa}}</td>
			<td><a class="glyphicon glyphicon-edit icon-align" title="Ver registro" href="{% url 'beneficios:update_beneficio' i.id %}"></a></td>
		</tr>
		{% empty %}
			vacío
		{% endfor %}
		</ul>
	</table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if registros.has_previous %}
            <a href="?page={{ registros.previous_page_number }}">anterior</a>
        {% endif %}
        <span class="current">
            Página {{ registros.number }} de {{ registros.paginator.num_pages }}.
        </span>
        {% if registros.has_next %}
            <a href="?page={{ registros.next_page_number }}">siguiente</a>
        {% endif %}
    </span>
</div>

<form action="{% url 'beneficios:add_beneficio' %}" method="get">
	{% csrf_token %}
	<button type="submit" class="btn btn-primary btn-block">Agregar</button>
</form>

{% endblock content %}