registros_victimas/generales/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base generales"""

urlpatterns = [
	url(r'^add_tipo_doc/$', 'generales.views.add_tipo_documento', name='add_tipo_documento'),
    url(r'^add_lugar_declaracion/$', 'generales.views.add_lugar_declaracion', name='add_lugar_declaracion'),
    url(r'^lista_lugares_declaracion/$', 'generales.views.lista_lugares_declaracion', name='lista_lugares_declaracion'),
    url(r'^lista_tipos_documento/$', 'generales.views.lista_tipos_documentos_generales', name='lista_tipos_documento'),
    url(r'^add_entidad_atencion/$', 'generales.views.add_entidad_atencion', name='add_entidad_atencion'),
    url(r'^matriz/$', 'generales.views.matriz', name='matriz'),
    url(r'^login_view/$', 'generales.views.login_view', name='login_view'),
    url(r'^index_view/$', 'generales.views.index_view', name='index_view'),
    url(r'^logout_view/$', 'generales.views.logout_view', name='logout_view'),
    url(r'^estado_clientes_view/$', 'generales.views.estado_clientes_view', name='estado_clientes_view'),
    url(r'^lista_notificaciones/(?P<id>\d+)/$', 'generales.views.lista_notificaciones', name='lista_notificaciones'),
    url(r'^notificaciones/$', 'generales.views.notificaciones', name='notificaciones'),
    url(r'^info/$', 'generales.views.info', name='info'),
]

registros_victimas/registros_victimas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^generales/', include('generales.urls', namespace='generales')),
    url(r'^solicitantes/', include('solicitantes.urls', namespace='solicitantes')),
    url(r'^beneficios/', include('beneficios.urls', namespace='beneficios')),
    url(r'^admin/', include(admin.site.urls)),
]

registros_victimas/solicitantes/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base solicitantes"""

urlpatterns = [
	url(r'^add_informacion_solicitante/$', 'solicitantes.views.add_informacion_solicitante', name='add_informacion_solicitante'),
	url(r'^add_declaracion/$', 'solicitantes.views.add_declaracion', name='add_declaracion'),
    url(r'^add_asociado_declarante/$', 'solicitantes.views.add_asociado', name='add_asociado_declarante'),
    url(r'^add_beneficio_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_beneficio_asociado', name='add_beneficio_asociado'),
    url(r'^add_discapacidad_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_discapacidad_asociado', name='add_discapacidad_asociado'),
    url(r'^add_etnia_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_etnia_asociado', name='add_etnia_asociado'),
    url(r'^add_correccion_declaracion/$', 'solicitantes.views.add_correccion_declaracion', name='add_correccion_declaracion'),
	url(r'^add_hecho_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_hecho_asociado', name='add_hecho_asociado'),
	url(r'^add_hecho_declarante/(?P<id>\d+)/$', 'solicitantes.views.add_hecho_declarante', name='add_hecho_declarante'),
    url(r'^add_informacion_solicitante/$', 'solicitantes.views.add_informacion_solicitante', name='add_informacion_solicitante'),
	url(r'^add_intermediario/$', 'solicitantes.views.add_intermediario', name='add_intermediario'),
	url(r'^add_tipo_intermediario/$', 'solicitantes.views.add_tipo_intermediario', name='add_tipo_intermediario'),
	
    url(r'^lista_declarantes/$', 'solicitantes.views.lista_declarantes', name='lista_declarantes'),
	url(r'^lista_asociados_declarante/(?P<id>\d+)/$', 'solicitantes.views.lista_asociados_declarante', name='lista_asociados_declarante'),
    url(r'^lista_solicitantes/$', 'solicitantes.views.lista_solicitantes', name='lista_solicitantes'),
	url(r'^lista_intermediarios/$', 'solicitantes.views.lista_intermediarios', name='lista_intermediarios'),
	#url(r'^update_asociado_declarante/$', 'solicitantes.views.update_asociado_declarante', name='update_asociado_declarante'),	
    url(r'^delete_beneficio_asociado/(?P<idben>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_beneficio_asociado', name='delete_beneficio_asociado'),
    url(r'^delete_discapacidad_asociado/(?P<iddisc>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_discapacidad_asociado', name='delete_discapacidad_asociado'),
    url(r'^delete_etnia_asociado/(?P<idet>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_etnia_asociado', name='delete_etnia_asociado'),
    url(r'^delete_hecho_asociado/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_hecho_asociado', name='delete_hecho_asociado'),
    url(r'^delete_hecho_declarante/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_hecho_declarante', name='delete_hecho_declarante'),


    url(r'^update_asociado_declarante/(?P<id>\d+)/$', 'solicitantes.views.update_asociado_declarante', name='update_asociado_declarante'),
    url(r'^update_beneficio_asociado/(?P<idben>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_beneficio_asociado', name='update_beneficio_asociado'),
    url(r'^update_discapacidad_asociado/(?P<iddisc>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_discapacidad_asociado', name='update_discapacidad_asociado'),
    url(r'^update_etnia_asociado/(?P<idet>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_etnia_asociado', name='update_etnia_asociado'),
    url(r'^update_hecho_asociado/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_hecho_asociado', name='update_hecho_asociado'),
    url(r'^update_hecho_declarante/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_hecho_declarante', name='update_hecho_declarante'),
    url(r'^update_declarante/(?P<id>\d+)/$', 'solicitantes.views.update_declarante', name='update_declarante'),
    url(r'^update_informacion_solicitante/(?P<id>\d+)/$', 'solicitantes.views.update_informacion_solicitante', name='update_informacion_solicitante'),
    url(r'^update_intermediario/(?P<id>\d+)/$', 'solicitantes.views.update_intermediario', name='update_intermediario'),

    #url(r'^solicitud_view/$', 'solicitantes.views.solicitud_view', name='solicitud_view'),

]

registros_victimas/solicitantes/views.py
# -*- coding: 850 -*-
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.template import RequestContext
from solicitantes.models import *
from beneficios.models import *
from solicitantes.forms import *
from django.forms import ModelForm
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import logging
import time

logger = logging.getLogger(__name__)

"""La función hace una captura de la entidad DeclarantesRegistrados de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_declarantes(request):
    declaraciones = TomaDeclaracion.objects.all()
    paginator = Paginator(declaraciones, 10) # muestra 10 contactos por página

    page = request.GET.get('page')
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_declarantes.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función hace una captura de la entidad Solicitudes de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_solicitantes(request):
    solicitantes = InformacionSolicitante.objects.all()
    paginator = Paginator(solicitantes, 10) # muestra 10 contactos por página

    page = request.GET.get('page')
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_solicitantes.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función hace una captura de la entidad AsociadosDeclarante de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_asociados_declarante(request, id):
    asociados = AsociadoDeclarante.objects.filter(declaracion__id=id)
    declarante = TomaDeclaracion.objects.get(id=id)
    return render_to_response(
        'lista_asociados_declarante.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función hace una captura de la entidad Intermediarios de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_intermediarios(request):
    intermediarios = Intermediario.objects.all()
    paginator = Paginator(intermediarios, 10) # muestra 10 contactos por página

    page = request.GET.get('page')
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_intermediarios.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función agrega un nuevo registro a la entidad de la base de datos correspondiente, el proceso de validación se hace
mediante un formulario estructurado a partir de la misma entidad de la base de datos."""
def add_asociado(request):
    informacion = "inicializando"
    titulo="Nuevo asociado"    
    if request.method == 'GET':
        form = asociadoForm()
        ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
        return render_to_response('add.html', 
            ctx,
            context_instance=RequestContext(request)
        )
    else:
        form = asociadoForm(request.POST)
        try:
            mydate = time.strptime(request.POST['fecha_nacimiento_asociado'], '%d-%m-%Y')
            if form.is_valid():
                form.save()
                informacion = "Guardado"
            else:
                informacion = "Error"
        except Exception, e:
            informacion = "DateError"
        
        return render_to_response(
            'add.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
    return render_to_response('add.html', 
        ctx,
        context_instance=RequestContext(request)
    )


"""La función captura un registro de la entidad seleccionado para ser modificado a partir de su identificador, presenta
un formulario estructurado a partir del modelo correspondiente con los campos presentados en el registro y permite hacer
cambios para luego ser almacenados en la base de datos."""
def update_asociado_declarante(request, id):
    print "asociado"
    print id
    asociado = AsociadoDeclarante.objects.get(id=id)
    informacion = "Procesando"
    titulo="Actualizar datos del asociado"

    hechosAsociado = HechoAsociado.objects.filter(asociado_id=id)#busca los hechos victimizarios relacionados al asociado
    hechosVictimizarios = HechoVictimizario.objects.all()
    ids = []#guarda el id de cada hecho para poder modificarlo posteriormente
    nombres = []#guarda los nombres de los hechos victimizarios asociados
    hechos = []
    for i in hechosAsociado:
        for j in hechosVictimizarios:
            if i.hecho_id == j.id:
                nombres.append(j.descripcion_hecho)
                ids.append(i.id)

    index = 0
    for i in hechosAsociado:
        var = [nombres[index], ids[index]]
        hechos.append(var)
        index += 1
    
    beneficiosAsociado = BeneficioAsociado.objects.filter(asociado_id=id)#busca los beneficios relacionados al asociado
    beneficiosVictima = BeneficioVictima.objects.all()
    ids = []#guarda el id de cada beneficio para poder modificarlo posteriormente
    nombres = []#almacena el nombre de los beneficios
    estados = []#almacena los estados actuales de cada beneficio al que se encuentra registrado el asociado
    beneficios = []
    for i in beneficiosAsociado:#busca los beneficios del asociado
        for j in beneficiosVictima:
            if i.beneficio_id == j.id:
                nombres.append(j.nombre_programa)
                estados.append(i.estado_actual_beneficio)
                ids.append(i.id)
    index = 0
    for i in beneficiosAsociado:
        var = [nombres[index], estados[index], ids[index]]
        beneficios.append(var)
        index += 1

    etniasAsociado = EtniaAsociado.objects.filter(asociado_id=id)#busca los grupos etnicos a los que pertenece el asociado
    preferenciasEtnicas = PreferenciaEtnica.objects.all()
    ids = []#guarda el id de cada etnia para poder modificarlo posteriormente
    nombres = []#almacena el nombre de las etnias
    etnias = []
    for i in etniasAsociado:#busca loas etnias del asociado
        for j in preferenciasEtnicas:
            if i.etnia_id == j.id:
                nombres.append(j.nombre_etnia)
                ids.append(i.id)
    index = 0
    for i in etniasAsociado:
        var = [nombres[index], ids[index]]
        etnias.append(var)
        index += 1

    discapacidadesAsociado = DiscapacidadAsociado.objects.filter(asociado_id=id)#busca las discapacidades que registra el asociado
    discapacidadesVictima = Discapacidad.objects.all()
    ids = []#guarda el id de cada discapacidad para poder modificarlo posteriormente
    nombres = []#almacena el nombre de las discapacidades
    discapacidades = []
    for i in discapacidadesAsociado:#busca las discapacidades del asociado
        for j in discapacidadesVictima:
            if i.discapacidad_id == j.id:
                nombres.append(j.tipo_discapacidad)
                ids.append(i.id)
    index = 0
    for i in discapacidadesAsociado:
        var = [nombres[index], ids[index]]
        discapacidades.append(var)
        index += 1

    if request.method == 'GET':
        form = asociadoForm(instance=asociado)
    else:
        form = asociadoForm(request.POST, instance=asociado)
        try:
            mydate = time.strptime(request.POST['fecha_nacimiento_asociado'], '%d-%m-%Y')
            if form.is_valid():
                form.save()
                informacion = "Guardado"
            else:
                informacion = "Error"
        except Exception, e:
            informacion = "DateError"
        return render_to_response(
            'add_form_asociados.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    return render_to_response('add_form_asociados.html', 
        locals(),
        context_instance=RequestContext(request)
    )
  

"""La función agrega un nuevo registro a la entidad de la base de datos correspondiente, el proceso de validación se hace
mediante un formulario estructurado a partir de la misma entidad de la base de datos."""
def add_beneficio_asociado(request, id):
    informacion = "inicializando"
    titulo="Asignar beneficio"
    if request.method == 'GET':
        form = beneficioAsociadoForm()
        ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
        return render_to_response('add.html', 
            ctx,
            context_instance=RequestContext(request)
        )
    else:
        form = beneficioAsociadoForm(request.POST)
        if form.is_valid():
            beneficio = form.save(commit=False)
            beneficio.asociado_id = id
            beneficio.save()#se almacena el hecho victimizario del declarante
            informacion = "Guardado"
            return render_to_response(
                'volver_asociado.html', 
                locals(),
                context_instance=RequestContext(request)
            )
        else:
            informacion = "Error"
            return render_to_response(
                'add.html', 
                locals(),
                context_instance=RequestContext(request)
            )
    return render_to_response('add.html', 
        locals(),
        context_instance=RequestContext(request)
    )

registros_victimas/solicitantes/templates/add_form_asociados.html
{% extends 'base.html' %}

{% block content %}

 
<input id="reloadValue" type="hidden" name="reloadValue" value="" />
<form class="form-horizontal" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>{{ titulo }}</legend>
        {% for field in form %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label> 
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                        {% if field.required = True %}
                            <p class="help-inline"><small>dsfdfs</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        
       
    </fieldset><br>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary btn-block">Guardar Cambios</button>
    </div>
</form>


<br/>

 <div>
    <form action="." method="POST">
        <div style="width:100%; overflow: scroll; overflow-y: hidden;">
        <legend>Beneficios:</legend>
        <table class="table table-bordered table-hover tabla">
            <ul>
            <tr>
               <th>Beneficio</th>
               <th>Estado actual</th>
               <th>Id beneficio del asociado</th>
               <th colspan="2">Accion</th>
            </tr>
            
            {% for i in beneficios %}
                    <tr>
                    {% for k in i %}
                        <td>{{k}}</td>
                        {% if k <= 1000000 %}
                            <td><a class="glyphicon glyphicon-edit icon-align" title="Editar registro"  href="{% url 'solicitantes:update_beneficio_asociado' k asociado.id %}"></a></td>
                            <td>
                                <a style="align: center;" class="glyphicon glyphicon-trash icon-align" title="Eliminar registro" onClick="swal({ title: 'Realmente quiere eliminar el registro?', text: 'Una vez eliminado no se podrá recuperar', type: 'warning', showCancelButton: true, cancelButtonText: 'No borrar', confirmButtonColor: '#DD6B55', confirmButtonText: 'Si, borrar', closeOnConfirm: false }, function(){
                                location.href='{% url 'solicitantes:delete_beneficio_asociado' k asociado.id %}';});"></a>
                            </td>
                        {% endif %}
                    {% endfor %}

                    </tr>
                    {% empty %}
                        vacío
                    {% endfor %}
            </ul>
        </table>
    </div>
    </form>
    <form action="{% url 'solicitantes:add_beneficio_asociado' asociado.id %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar Beneficio</button>
    </form>
</div>

<br/>

<div>
    <form action="." method="POST">
        <div style="width:100%; overflow: scroll; overflow-y: hidden;">
        <legend>Hechos Victimizarios:</legend>
        <table class="table table-bordered table-hover tabla">
            <ul>
            <tr>
               <th>Hecho victimizario</th>
               <th>Id hecho</th>
               <th colspan="2">Accion</th>
            </tr>
            
            {% for i in hechos %}
                <tr>
                    {% for k in i %}
                        <td>{{ k }}</td>
                        {% if k <= 1000000 %}
                            <td><a class="glyphicon glyphicon-edit icon-align" title="Editar registro" href="{% url 'solicitantes:update_hecho_asociado' k asociado.id %}"></a></td>
                            <td>
                                <a style="align: center;" class="glyphicon glyphicon-trash icon-align" title="Eliminar registro" onClick="swal({ title: 'Realmente quiere eliminar el registro?', text: 'Una vez eliminado no se podrá recuperar', type: 'warning', showCancelButton: true, cancelButtonText: 'No borrar', confirmButtonColor: '#DD6B55', confirmButtonText: 'Si, borrar', closeOnConfirm: false }, function(){
                                location.href='{% url 'solicitantes:delete_hecho_asociado' k asociado.id %}';});"></a>
                            </td>
                            
                        {% endif %}
                    {% endfor %}
            {% empty %}
                vacío
            {% endfor %}
                    </tr>
            </ul>
        </table>
        </div>
    </form>
    <form action="{% url 'solicitantes:add_hecho_asociado' asociado.id %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar hecho victimizario</button>
    </form>
</div>

<br/>

<div>
    <form action="." method="POST">
        <div style="width:100%; overflow: scroll; overflow-y: hidden;">
        <legend>Etnias:</legend>
        <table class="table table-bordered table-hover tabla">
            <ul>
            <tr>
               <th>Etnia</th>
               <th>Id etnia del asociado</th>
               <th colspan="2">Accion</th>
            </tr>
            
            {% for i in etnias %}
                <tr>
                {% for k in i %}
                    <td>{{k}}</td>
                    {% if k <= 1000000 %}
                        <td><a class="glyphicon glyphicon-edit icon-align" title="Editar registro" href="{% url 'solicitantes:update_etnia_asociado' k asociado.id %}"></a></td>
                        <td>
                            <a style="align: center;" class="glyphicon glyphicon-trash icon-align" title="Eliminar registro" onClick="swal({ title: 'Realmente quiere eliminar el registro?', text: 'Una vez eliminado no se podrá recuperar', type: 'warning', showCancelButton: true, cancelButtonText: 'No borrar', confirmButtonColor: '#DD6B55', confirmButtonText: 'Si, borrar', closeOnConfirm: false }, function(){
                            location.href='{% url 'solicitantes:delete_etnia_asociado' k asociado.id %}';
                            });"></sa>
                        </td>
                    {% endif %}
                {% endfor %}

                </tr>
                {% empty %}
                    vacío
                {% endfor %}
            </ul>
        </table>
    </div>
    </form>
    <form action="{% url 'solicitantes:add_etnia_asociado' asociado.id%}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar Etnia</button>
    </form>
</div>

<br/>

<div>
    <form action="." method="POST">
        <div style="width:100%; overflow: scroll; overflow-y: hidden;">
        <legend>Discapacidades:</legend>
        <table class="table table-bordered table-hover tabla">
            <ul>
            <tr>
               <th>Discapacidad</td>
               <th>Id discapacidad del asociado</td>
               <th colspan="2">Accion</td>
            </tr>
            
            {% for i in discapacidades %}
                    <tr>
                    {% for k in i %}
                        <td>{{k}}</td>
                        {% if k <= 1000000 %}
                            <td><a class="glyphicon glyphicon-edit icon-align" title="Editar registro" href="{% url 'solicitantes:update_discapacidad_asociado' k asociado.id %}"></a></td>
                            <td>
                                <a style="align: center;" class="glyphicon glyphicon-trash icon-align" title="Eliminar registro" onClick="swal({ title: 'Realmente quiere eliminar el registro?', text: 'Una vez eliminado no se podrá recuperar', type: 'warning', showCancelButton: true, cancelButtonText: 'No borrar', confirmButtonColor: '#DD6B55', confirmButtonText: 'Si, borrar', closeOnConfirm: false }, function(){
                                location.href='{% url 'solicitantes:delete_discapacidad_asociado' k asociado.id %}';});"></a>
                            </td>
                        {% endif %}
                    {% endfor %}

                    </tr>
                    {% empty %}
                        vacío
                    {% endfor %}
            </ul>
        </table>
        </div>
    </form>
    <form action="{% url 'solicitantes:add_discapacidad_asociado' asociado.id %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar Discapacidad</button>
    </form>
</div>

{% if "Guardado" in informacion %}
    <script type="text/javascript">
    swal('Guardado!', 'El registro ha sido guardado satisfactoriamente', 'success');
    </script>
{% endif %}
{% if "Eliminado" in informacion %}
    <script type="text/javascript">
    swal('Eliminado!', 'El registro se ha borrado satisfactoriamente', 'sucess');
    </script>
{% endif %}
{% if "Error" in informacion %}
    <script type="text/javascript">
    swal('Error!', 'Verifique que los campos se encuentren bien diligenciados', 'error');
    </script>
{% endif %}
{% if "DateError" in informacion %}
    <script type="text/javascript">
    swal('Error!', 'Los formatos de fecha son inválidos, el formato correcto es "dd-mm-aaaa"', 'error');
    </script>
{% endif %}

{% endblock content %}


registros_victimas/solicitantes/templates/lista_declarantes.html
{% extends 'base.html' %}

{% block content %}
<div>
	<h3>Declarantes</h3>
		<div style="width:100%; overflow: scroll; overflow-y: hidden;">
		<table class="table table-bordered table-hover table-striped table-reflow tabla">
	  		<ul>
	  		<tr>
				<th>Código</th>
				<th>Primer nombre</th>
				<th>Demás nombres</th>
				<th>Primer apellido</th>
				<th>Segundo apellido</th>
				<th>Número de documento</th>
				<th colspan="2">Acciones</th>
			</tr>
		{% for i in registros %}
		<tr>
			<td>{{i.codigo_declaracion}}</td>
			<td>{{i.primer_nombre_declarante}}</td>
			<td>{{i.demas_nombres_declarante}}</td>
			<td>{{i.primer_apellido_declarante}}</td>
			<td>{{i.segundo_apellido_declarante}}</td>
			<td>{{i.numero_documento_declarante}}</td>
			<td><a class="glyphicon glyphicon-list-alt icon-align" title="Ver asociados del declarante" href="{% url 'solicitantes:lista_asociados_declarante' i.id %}"></a></td>
			<td><a class="glyphicon glyphicon-edit icon-align" title="Ver registro" href="{% url 'solicitantes:update_declarante' i.id %}"></a></td>
		</td>
		</td>
		{% empty %}
			vacío
		{% endfor %}
		</ul>

	</table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if registros.has_previous %}
            <a href="?page={{ registros.previous_page_number }}">anterior</a>
        {% endif %}
        <span class="current">
            Página {{ registros.number }} de {{ registros.paginator.num_pages }}.
        </span>
        {% if registros.has_next %}
            <a href="?page={{ registros.next_page_number }}">siguiente</a>
        {% endif %}
    </span>
</div>

<form action="{% url 'solicitantes:add_declaracion' %}" method="get">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-block">Agregar</button>
</form>

{% endblock content %}

registros_victimas/solicitantes/templates/volver_asociado.html
{% extends 'base.html' %}

{% block content %}

<form class="form-horizontal" action="{% url 'solicitantes:update_asociado_declarante' id %}" method="get">
    {% csrf_token %}
    
    <div class="form-actions">
        <button type="submit" class="btn btn-primary btn-block">Volver al registro del asociado</button>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <br><br><br><br><br>
    </div>
    <script type="text/javascript">swal('Hecho');</script>
</form>

{% if "Guardado" in informacion %}
    <script type="text/javascript">
    swal('Guardado!', 'El registro ha sido guardado satisfactoriamente', 'success');
    </script>
{% endif %}
{% if "Eliminado" in informacion %}
    <script type="text/javascript">
    swal('Eliminado!', 'El registro se ha borrado satisfactoriamente', 'sucess');
    </script>
{% endif %}
{% if "Error" in informacion %}
    <script type="text/javascript">
    swal('Error!', 'Verifique que los campos se encuentren bien diligenciados', 'error');
    </script>
{% endif %}

{% endblock content %}
