registros_victimas/beneficios/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base beneficios"""

urlpatterns = [
    url(r'^add_beneficio/$', 'beneficios.views.add_beneficio', name='add_beneficio'),
    url(r'^lista_beneficios/$', 'beneficios.views.lista_beneficios', name='lista_beneficios'),
    url(r'^update_beneficio/(?P<id>\d+)/$', 'beneficios.views.update_beneficio', name='update_beneficio'),
]

registros_victimas/generales/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base generales"""

urlpatterns = [
	url(r'^add_tipo_doc/$', 'generales.views.add_tipo_documento', name='add_tipo_documento'),
    url(r'^add_lugar_declaracion/$', 'generales.views.add_lugar_declaracion', name='add_lugar_declaracion'),
    url(r'^lista_lugares_declaracion/$', 'generales.views.lista_lugares_declaracion', name='lista_lugares_declaracion'),
    url(r'^lista_tipos_documento/$', 'generales.views.lista_tipos_documentos_generales', name='lista_tipos_documento'),
    url(r'^add_entidad_atencion/$', 'generales.views.add_entidad_atencion', name='add_entidad_atencion'),
    url(r'^matriz/$', 'generales.views.matriz', name='matriz'),
    url(r'^login_view/$', 'generales.views.login_view', name='login_view'),
    url(r'^index_view/$', 'generales.views.index_view', name='index_view'),
    url(r'^logout_view/$', 'generales.views.logout_view', name='logout_view'),
    url(r'^estado_clientes_view/$', 'generales.views.estado_clientes_view', name='estado_clientes_view'),
    url(r'^lista_notificaciones/(?P<id>\d+)/$', 'generales.views.lista_notificaciones', name='lista_notificaciones'),
    url(r'^notificaciones/$', 'generales.views.notificaciones', name='notificaciones'),
    url(r'^info/$', 'generales.views.info', name='info'),
]

registros_victimas/registros_victimas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^generales/', include('generales.urls', namespace='generales')),
    url(r'^solicitantes/', include('solicitantes.urls', namespace='solicitantes')),
    url(r'^beneficios/', include('beneficios.urls', namespace='beneficios')),
    url(r'^admin/', include(admin.site.urls)),
]

registros_victimas/solicitantes/urls.py
# -*- coding: 850 -*-
from django.conf.urls import include, url

"""Cada url crea una nueva dirección en el sitio a partir de la dirección base solicitantes"""

urlpatterns = [
	url(r'^add_informacion_solicitante/$', 'solicitantes.views.add_informacion_solicitante', name='add_informacion_solicitante'),
	url(r'^add_declaracion/$', 'solicitantes.views.add_declaracion', name='add_declaracion'),
    url(r'^add_asociado_declarante/$', 'solicitantes.views.add_asociado', name='add_asociado_declarante'),
    url(r'^add_beneficio_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_beneficio_asociado', name='add_beneficio_asociado'),
    url(r'^add_discapacidad_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_discapacidad_asociado', name='add_discapacidad_asociado'),
    url(r'^add_etnia_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_etnia_asociado', name='add_etnia_asociado'),
    url(r'^add_correccion_declaracion/$', 'solicitantes.views.add_correccion_declaracion', name='add_correccion_declaracion'),
	url(r'^add_hecho_asociado/(?P<id>\d+)/$', 'solicitantes.views.add_hecho_asociado', name='add_hecho_asociado'),
	url(r'^add_hecho_declarante/(?P<id>\d+)/$', 'solicitantes.views.add_hecho_declarante', name='add_hecho_declarante'),
    url(r'^add_informacion_solicitante/$', 'solicitantes.views.add_informacion_solicitante', name='add_informacion_solicitante'),
	url(r'^add_intermediario/$', 'solicitantes.views.add_intermediario', name='add_intermediario'),
	url(r'^add_tipo_intermediario/$', 'solicitantes.views.add_tipo_intermediario', name='add_tipo_intermediario'),
	
    url(r'^lista_declarantes/$', 'solicitantes.views.lista_declarantes', name='lista_declarantes'),
	url(r'^lista_asociados_declarante/(?P<id>\d+)/$', 'solicitantes.views.lista_asociados_declarante', name='lista_asociados_declarante'),
    url(r'^lista_solicitantes/$', 'solicitantes.views.lista_solicitantes', name='lista_solicitantes'),
	url(r'^lista_intermediarios/$', 'solicitantes.views.lista_intermediarios', name='lista_intermediarios'),
	#url(r'^update_asociado_declarante/$', 'solicitantes.views.update_asociado_declarante', name='update_asociado_declarante'),	
    url(r'^delete_beneficio_asociado/(?P<idben>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_beneficio_asociado', name='delete_beneficio_asociado'),
    url(r'^delete_discapacidad_asociado/(?P<iddisc>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_discapacidad_asociado', name='delete_discapacidad_asociado'),
    url(r'^delete_etnia_asociado/(?P<idet>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_etnia_asociado', name='delete_etnia_asociado'),
    url(r'^delete_hecho_asociado/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_hecho_asociado', name='delete_hecho_asociado'),
    url(r'^delete_hecho_declarante/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.delete_hecho_declarante', name='delete_hecho_declarante'),


    url(r'^update_asociado_declarante/(?P<id>\d+)/$', 'solicitantes.views.update_asociado_declarante', name='update_asociado_declarante'),
    url(r'^update_beneficio_asociado/(?P<idben>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_beneficio_asociado', name='update_beneficio_asociado'),
    url(r'^update_discapacidad_asociado/(?P<iddisc>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_discapacidad_asociado', name='update_discapacidad_asociado'),
    url(r'^update_etnia_asociado/(?P<idet>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_etnia_asociado', name='update_etnia_asociado'),
    url(r'^update_hecho_asociado/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_hecho_asociado', name='update_hecho_asociado'),
    url(r'^update_hecho_declarante/(?P<idhec>\d+)/(?P<id>\d+)/$', 'solicitantes.views.update_hecho_declarante', name='update_hecho_declarante'),
    url(r'^update_declarante/(?P<id>\d+)/$', 'solicitantes.views.update_declarante', name='update_declarante'),
    url(r'^update_informacion_solicitante/(?P<id>\d+)/$', 'solicitantes.views.update_informacion_solicitante', name='update_informacion_solicitante'),
    url(r'^update_intermediario/(?P<id>\d+)/$', 'solicitantes.views.update_intermediario', name='update_intermediario'),

    #url(r'^solicitud_view/$', 'solicitantes.views.solicitud_view', name='solicitud_view'),

]

registros_victimas/generales/views.py
# -*- coding: 850 -*-
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.core.urlresolvers import reverse, resolve
from django.template import RequestContext
from generales.models import *
from beneficios.models import *
from solicitantes.models import *
from generales.forms import *
from django.db.models import Q
from datetime import datetime,date
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv


"""La función permite alternar el estado de recepción de solicitudes por parte de los usuarios
invidados, donde activo es un estado en el que se permiten estas e inactivo donde no"""
def estado_clientes_view(request):
    sistema = InformacionSolicitante.objects.get(id=0)#se obtiene el registro cero para comprobar si se están aceptando solicitudes
    estado = sistema.descripcion#corresponde al estado actual del sistema de registro de solicitudes por parte de los usuarios
    if request.method == 'GET':
        return render_to_response('control_usuarios.html', 
            locals(), 
            context_instance=RequestContext(request)
        )
    else:
        if "Activo" in estado:
            sistema.descripcion = "Bloqueado"
            sistema.save() 
            estado = sistema.descripcion
        else:
            sistema.descripcion = "Activo"
            sistema.save()
            estado = sistema.descripcion
        return render_to_response(
            'control_usuarios.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    return render_to_response(
        'control_usuarios.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función dirige a una página en la cual se encuentra la información completa
correspondiente a la ley 1448 de 2011"""
def info(request):
    return render_to_response(
        'info.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función hace una captura de la entidad LugaresDeclaracion de la base de datos y presenta todos sus registros
en una lista paginada."""
def lista_lugares_declaracion(request):
    lugares = LugarDeclaracion.objects.all()
    paginator = Paginator(lugares, 15) # muestra 15 contactos por página

    page = request.GET.get('page')
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_lugares_declaracion.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


def lista_tipos_documentos_generales(request):
    tipos_documentos = TipoDocumento.objects.all()

    return render_to_response(
        'lista_tipos_documentos_generales.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""presenta una lista con tres elementos los cuales son solocitantes atendidos, en revisión y pendientes,
la función hace un conteo de los solicitantes correspondientes al estado y presenta el número de estos
dentro de cada elemento de la lista correspondiente"""
def lista_notificaciones(request, id):
    titulo = ''
    #obtiene el valor seleccionado por el usuario donde 1 es atendidos, 2 pendientes y 3 en revisión
    if '1' in id:
        atendidos = InformacionSolicitante.objects.filter(estado_revision='Atendido')        
        filtro = atendidos#la variable filtro unifica el resultado independientemente del seleccionado
        #esto se hace para usar una sola plantilla html para cualquier filtro
        titulo = 'Solicitantes atendidos'
    if '2' in id:
        pendientes = InformacionSolicitante.objects.filter(estado_revision='Pendiente')
        filtro = pendientes
        titulo = 'Solicitantes pendientes'
    if '3' in id:
        revisados = InformacionSolicitante.objects.filter(estado_revision='En revision')
        filtro = revisados
        titulo = 'Solicitantes en revisión'
    #hace proceso de paginación por si hay muchos registros para que sean presentados por partes
    paginator = Paginator(filtro, 10) # muestra 10 contactos por página
    page = request.GET.get('page')#obtiene el número de página actual seleccionada por el usuario
    try:
        registros = paginator.page(page)
    except PageNotAnInteger:
        registros = paginator.page(1)
    except EmptyPage:
        registros = paginator.page(paginator.num_pages)
    return render_to_response(
        'lista_notificaciones.html', 
        locals(), 
        context_instance=RequestContext(request)
    )


"""La función hace un conteo de los solicitantes en cada estado, su objetivo es enviar estos valores de forma parametrizada para
presentarse por la función lista_notificaciones"""
def notificaciones(request):
    #filtra los registros de solicitudes por el estado actual
    atendidos = InformacionSolicitante.objects.filter(estado_revision='Atendido')
    pendientes = InformacionSolicitante.objects.filter(estado_revision='Pendiente')
    revisados = InformacionSolicitante.objects.filter(estado_revision='En revision')

    atend = len(atendidos)#cuenta cuantos registros hay en cada filtro
    pend = len(pendientes)
    revis = len(revisados)
    return render_to_response(
        'notificaciones.html', 
        locals(), 
        context_instance=RequestContext(request)
    )
    

"""La función agrega un nuevo registro a la entidad de la base de datos correspondiente, el proceso de validación se hace
mediante un formulario estructurado a partir de la misma entidad de la base de datos."""
def add_entidad_atencion(request):
    informacion = "inicializando"
    titulo="Nueva entidad de atención"
    if request.method == 'GET':
        form = entidadAtencionForm()
        ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
        return render_to_response('add.html', 
            ctx, 
            context_instance=RequestContext(request)
        )
    else:
        form = entidadAtencionForm(request.POST) 
        info = "inicializando"
        if form.is_valid():
            form.save()
            informacion = "Guardado"
        else:
            informacion = "Error"
        return render_to_response(
            'add.html', 
            locals(),
            context_instance=RequestContext(request)
        )
    ctx = {'form':form, 'informacion':informacion, 'titulo': titulo}
    return render_to_response('add.html', 
        ctx,
        context_instance=RequestContext(request)
    )        


"""La función agrega un nuevo registro a la entidad de la base de datos correspondiente, el proceso de validación se hace
mediante un formulario estructurado a partir de la misma entidad de la base de datos."""
def add_tipo_documento(request):
    if request.method == "POST":
        form = addTipoDocumentoForm(request.POST) 
        info = "inicializando"
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            abreviacion = form.cleaned_data['abreviacion']
            t = TipoDocumento()
            t.nombre = nombre
            t.abreviacion = abreviacion
            t.save()
            info = "Guardado"
        else:
            info= "Error"
        form = addTipoDocumentoForm()
        ctx = {'form':form, 'informacion':info}
        return render_to_response('add.html', 
            ctx, 
            context_instance=RequestContext(request)
        )

    else:
        form = addTipoDocumentoForm()
        ctx = {'form':form}
        return render_to_response('add.html', 
            ctx, 
            context_instance=RequestContext(request)
        )


"""La función matriz estructura un arreglo de arreglos donde se evalúa en 4 niveles de inmersión las relaciones entre
los asociados del declarante y los beneficios otorgados para estos, los datos se estructuran de forma horizontal tomando
los datos de cada beneficio y haciendo cálculos de sus características a partir de los presupuestos disponibles y los 
enfoques diferenciales registrados en cada asociado correspondiente, además asocia el derecho involucrado en el beneficio en 
cuestión, y de forma vertical haciendo una pila de los beneficios que registran asociados en estado de atención activo."""
def matriz(request):    
    
    beneficiosAsociados = BeneficioAsociado.objects.all()
    hechosAsociados = HechoAsociado.objects.all()
    etniasAsociados = EtniaAsociado.objects.all()
    discapacidadesAsociados = DiscapacidadAsociado.objects.all()
    derechos = Derecho.objects.all()
    beneficiosDerechoSeleccionado = BeneficioVictima.objects.all()

    derechosBeneficio = []
    condicionesProblematicas = []
    nombresBeneficios = []
    estadosGestionProgramas = []
    metasProgramas = []
    avancesMetas = []
    indicadores = []
    participacionesNacional = []
    participacionesDepartamental = []
    participacionesMunicipal = []
    cooperacionesInternacional = []
    participacionesOtros = []

    coofinanciacionesNacionales = []
    fosygaEtesa = []
    otrosRecursosNacionales = []
    totalPresupuestosNacionales = []
    coofinanciacionesDepartamentales = []
    otrosRecursosDepartamentales = []
    totalPresupuestosDepartamentales = []
    recursosPropios = []
    sistemasGeneralesParticipaciones = []
    regaliasMunicipales = []
    creditosMunicipales = []
    otrosRecursosMunicipales = []
    totalPresupuestosMunicipales = []
    empresasPrivadas = []
    cooperacionesOtros = []
    otrosOtros = []
    totalPresupuestosOtros = []
    totalPresupuestos = []

    beneficioVictimasDesplazamiento = []
    beneficioVictimasOtros = []
    cantidadAsociadosBeneficio = []

    afrocolombianosDesplazados = []

registros_victimas/generales/templates/base.html
{% load staticfiles %}
<html>
  <head>
      <meta name="tipo_contenido"  content="text/html;" http-equiv="content-type" charset="utf-8">
      <title>Registro de victimas</title>

      <link rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap-theme.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <!--plugins para las alertas-->
      <link rel="stylesheet" type="text/css" href="{% static 'sweetalert/dist/sweetalert.css' %}">
      <script src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script> 
      <!--plugins para los desplegables-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <!--plugins para las tablas-->
      <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
      <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
      <!--<script type="text/javascript" src="{% static 'js/table.js' %}"></script>-->
      <script type="text/javascript" src="../static/js/table.js"></script>
      
  </head> 
  <body class="margenes">
    <div class="">
      <img class="img-responsive superior" alt="">
    </div>

    <ul class="nav navbar-nav navbar-right" style="margin-right: 5px">
          
    </ul>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">SIGIVIC</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Inicio</a></li>
          {% if user.is_authenticated and user.is_staff == True %}
          <li class="dropdown">
            <a class="dropdown-toggle glyphicon glyphicon-tasks" data-toggle="dropdown" href="#"> Funciones
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a class="glyphicon glyphicon-eye-close" href="{% url 'generales:estado_clientes_view' %}"> Atención en línea</a></li>
              <li><a href="{% url 'generales:matriz' %}" class="glyphicon glyphicon-th" title="Matriz de beneficios"> Matriz de beneficios</a></li>
            <li><a href="{% url 'generales:notificaciones' %}" class="glyphicon glyphicon-alert" title="Matriz de beneficios"> Notificaciones</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle glyphicon glyphicon-list" data-toggle="dropdown" title="Listas de registros" href="#"> Listas
                    <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="http://localhost:8000/beneficios/lista_beneficios/">Beneficios</a></li> 
              <li><a href="{% url 'solicitantes:lista_solicitantes' %}">Solicitantes</a></li> 
              <li><a href="{% url 'solicitantes:lista_declarantes' %}">Declarantes registrados</a></li> 
              <li><a href="{% url 'solicitantes:lista_intermediarios' %}">Intermediarios registrados</a></li> 
              <li><a href="{% url 'generales:lista_lugares_declaracion' %}">Lugares de declaración</a></li> 
            </ul>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle glyphicon glyphicon-plus" data-toggle="dropdown" title="Agregar registros" href="#"> Agregar
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'beneficios:add_beneficio' %}">Beneficio</a></li>
              <li><a href="{% url 'solicitantes:add_informacion_solicitante' %}">Solicitante</a></li>
              <li><a href="{% url 'solicitantes:add_declaracion' %}">Declaracion</a></li>
              <li><a href="{% url 'solicitantes:add_asociado_declarante' %}">Asociado</a></li>
              <li><a href="{% url 'generales:add_entidad_atencion' %}">Entidad de atención</a></li>
              <li><a href="{% url 'solicitantes:add_intermediario' %}">Intermediario</a></li>
              <li><a href="{% url 'solicitantes:add_tipo_intermediario' %}">Tipo de intermediario</a></li>
              <li><a href="{% url 'generales:add_lugar_declaracion' %}">Lugar de declaración</a></li>
              <li><a href="{% url 'solicitantes:add_correccion_declaracion' %}">Corrección a una declaración</a></li> 
            </ul>
          </li>

          <li><a class="glyphicon glyphicon-exclamation-sign" href="{% url 'generales:info' %}"> Información</a></li> 
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">

          {% if user.is_authenticated %}
            <li><a href="{% url 'generales:index_view' %}"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
            <li><a href="http://localhost:8000/generales/logout_view"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>
          {% else %}
            <li><a href="http://localhost:8000/generales/login_view"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if user.is_authenticated and user.is_staff == True %}
    <div class="panel panel-primary">
      <div class="panel-head">Administrador</div>
      <div class="panel-body">

        <div class="contenido">
            {% include '_messages.html' %}
            {% block content %}
            
            {% endblock %}
        </div>

      </div>
    </div>
    {% endif %}

  </body>
   
        

    
    
  </div>
  <footer class="footer">
    <p class="navbar-text pull-left">© 2016 - SIGIVIC, Todos los derechos reservados</p>
  </footer>
</html>

registros_victimas/generales/templates/control_usuarios.html
{% extends 'base.html' %}

{% block title %}control de usuarios{% endblock title %}

{% block content %}
	{% if "Activo" in estado %}
		<legend>Actualmente se encuentra activo</legend><br/>
		<form action="{% url 'generales:estado_clientes_view' %}" method="POST">
	    	<input type="submit" id="image-habilitado" text="Habilitado" value=""></input><br/><br/>
			{% csrf_token %}
	    	Cualquier usuario puede realizar una solicitud en línea, haga click en la imágen si desea inhabilitar esta función.
	    </form>
	{% else %}
		<legend>Actualmente se encuentra inactivo</legend><br/>
		<form action="{% url 'generales:estado_clientes_view' %}" method="POST">
			<input type="submit" id="image-inhabilitado" text="Inhabilitado" value=""></input><br/><br/>
			{% csrf_token %}
	    	Los usuarios no pueden hacer solicitudes de declaración en línea, haga click en la imágen para permitir a los usuarios realizar solicitudes.
	    </form>
	{% endif %}
{% endblock content %}

registros_victimas/generales/templates/index.html
{% extends 'base.html' %}

{% block title %}Perfil de usuario{% endblock title %}

{% block content %}
<div class="page-header"><h2><h2>Perfil de usuario</h2></div>
    Nombre de usuario:<br/>{{ user.username }}<br><br>
    Correo electrónico:<br/>{{ user.email }}<br>
    
{% endblock content %}

registros_victimas/generales/templates/lista_lugares_declaracion - copia.html
{% extends 'base.html' %}

{% block content %}

<div>
	<table class="table table-bordered table-hover">
  		<ul>
		{% for i in lugares %}
		<tr>
			<td>{{i.id}}</td>
			<td>{{i.departamento_declaracion}}</td>
			<td>{{i.municipio_declaracion}}</td>
		</tr>
		{% empty %}
			vacío
		{% endfor %}
		</ul>
	</table>
    <form action="{% url 'generales:add_lugar_declaracion' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar</button>
    </form>
</div>

{% endblock content %}

registros_victimas/generales/templates/lista_lugares_declaracion.html
{% extends 'base.html' %}

{% block content %}
<div>
	<table class="table table-bordered table-hover tabla">
  		<ul>
  		<legend>Lugares de declaración</legend>
  		<tr>
			<th>ID</th>
			<th>Departamento</th>
			<th>Municipio</th>
		</tr>
		{% for i in registros %}
		<tr>
			<td>{{i.id}}</td>
			<td>{{i.departamento_declaracion}}</td>
			<td>{{i.municipio_declaracion}}</td>
		</tr>
		{% empty %}
			vacío
		{% endfor %}
		</ul>
	</table>


<div class="pagination">
    <span class="step-links">
        {% if registros.has_previous %}
            <a href="?page={{ registros.previous_page_number }}">anterior</a>
        {% endif %}
        <span class="current">
            Página {{ registros.number }} de {{ registros.paginator.num_pages }}.
        </span>
        {% if registros.has_next %}
            <a href="?page={{ registros.next_page_number }}">siguiente</a>
        {% endif %}
    </span>
</div>




    <form action="{% url 'generales:add_lugar_declaracion' %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Agregar</button>
    </form>
</div>

{% endblock content %}

registros_victimas/generales/templates/lista_notificaciones.html
{% extends 'base.html' %}

{% block content %}
<div style="width:100%; overflow: scroll; overflow-y: hidden;">
	<table class="table table-bordered table-hover tabla">
  		<h3>{{ titulo }}</h3>
  		<tr>
			<th>ID</th>
			<th>Declaración</th>
			<th>Tipo de documento</th>
			<th>Nombre</th>
			<th>Dirección</th>
			<th>Descripción</th>
			<th>Estado de revisión</th>
			<th>Acciones</th>
		</tr>
		{% for i in registros %}
		<tr>
			<td>{{i.id}}</td>
			<td>{{i.declaracion}}</td>
			<td>{{i.tipo_documento}}</td>
			<td>{{i.nombre}}</td>
			<td>{{i.direccion}}</td>
			<td>{{i.descripcion}}</td>
			<td>{{i.estado_revision}}</td>
			<td><a class="glyphicon glyphicon-edit icon-align" title="Ver registro" href="{% url 'solicitantes:update_informacion_solicitante' i.id %}"></a></td>
		</td>
		</td>
		{% empty %}
			vacío
		{% endfor %}
		</ul>
	</table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if registros.has_previous %}
            <a href="?page={{ registros.previous_page_number }}">anterior</a>
        {% endif %}
        <span class="current">
            Página {{ registros.number }} de {{ registros.paginator.num_pages }}.
        </span>
        {% if registros.has_next %}
            <a href="?page={{ registros.next_page_number }}">siguiente</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

registros_victimas/generales/templates/notificaciones.html
{% extends 'base.html' %}

{% block content %}
	<h3>Notificaciones de solicitantes</h3><br>
	<form action="{% url 'generales:lista_notificaciones' 1 %}" method="get">
        {% csrf_token %}
        <button type="submit" title="Ver registros" class="alert alert-success glyphicon glyphicon-eye-open"> Solicitantes Atendidos ({{ atend }})</button>
    </form>

    <form action="{% url 'generales:lista_notificaciones' 3 %}" method="get">
        {% csrf_token %}
        <button type="submit" title="Ver registros" class="alert alert-warning glyphicon glyphicon-eye-open"> Solicitantes En Revisión ({{ revis }})</button>
    </form>
		
    <form action="{% url 'generales:lista_notificaciones' 2 %}" method="get">
        {% csrf_token %}
        <button type="submit" title="Ver registros" class="alert alert-danger glyphicon glyphicon-eye-open"> Solicitantes Pendientes ({{ pend }})</button>
    </form>


{% endblock content %}